import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>

        <div className={styles.description}>

          <div>
            <Link
              href="/"
              className={styles.card}
              rel="noopener noreferrer"
            >
              <h2>
                Ir about <span>-&gt;</span>
              </h2>
            </Link>
          </div>
        </div>




      </main>
    </>
  )
}
